# Generated by Django 2.2.6 on 2019-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='关联的普通用户', max_length=30)),
                ('user', models.CharField(default='', help_text='管理员账号', max_length=30)),
                ('password', models.CharField(help_text='管理员密码', max_length=30)),
                ('auth', models.IntegerField(default=2, help_text='管理员权限 1：超级管理员 2：子管理员')),
            ],
        ),
        migrations.CreateModel(
            name='p_sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='农业信息网', help_text='网站名称', max_length=30)),
                ('dec', models.CharField(default='网站的描述', help_text='网站描述', max_length=500)),
                ('keyword', models.CharField(default='农产品交易,农业信息,供应信息,求购信息', help_text='网站关键词', max_length=30)),
                ('url', models.CharField(default='', help_text='网站域名', max_length=30)),
                ('img_limit', models.IntegerField(default=100, help_text='用户上传总图片限制/每天')),
                ('article_limit', models.IntegerField(default=10, help_text='用户发表文章限制/每天')),
            ],
        ),
    ]
