# Generated by Django 2.2.6 on 2019-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='关联的普通用户', max_length=30)),
                ('user', models.CharField(default='', help_text='管理员账号', max_length=30)),
                ('password', models.CharField(help_text='管理员密码', max_length=30)),
                ('auth', models.IntegerField(default=2, help_text='管理员权限 1：超级管理员 2：子管理员')),
            ],
        ),
    ]
