# Generated by Django 2.2.6 on 2019-10-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='农业信息网', help_text='网站名称', max_length=30)),
                ('dec', models.CharField(default='网站的描述', help_text='网站描述', max_length=500)),
                ('keyword', models.CharField(default='农产品交易,农业信息,供应信息,求购信息', help_text='网站关键词', max_length=30)),
                ('url', models.CharField(default='', help_text='网站域名', max_length=30)),
                ('img_limit', models.IntegerField(default=100, help_text='用户上传总图片限制/每天')),
                ('article_limit', models.IntegerField(default=10, help_text='用户发表文章限制/每天')),
            ],
        ),
    ]
