# Generated by Django 2.2.3 on 2019-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_product_child',
            name='p_id',
            field=models.IntegerField(help_text='父ID'),
        ),
    ]
