# Generated by Django 2.2.6 on 2019-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='文件名称', max_length=30)),
                ('username', models.CharField(help_text='关联用户', max_length=30)),
                ('path', models.CharField(help_text='文件路径', max_length=200)),
                ('create_time', models.CharField(default='0', help_text='创建时间', max_length=30)),
                ('update_time', models.CharField(default='0', help_text='修改时间', max_length=30)),
            ],
        ),
    ]
