# Generated by Django 2.2.3 on 2019-10-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p_admin',
        ),
    ]
