# Generated by Django 2.2.3 on 2019-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_p_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_message',
            name='m_address_city',
            field=models.CharField(default='', help_text='所属地区代码(市级)', max_length=80),
        ),
        migrations.AddField(
            model_name='p_message',
            name='m_address_province',
            field=models.CharField(default='', help_text='所属地区代码(省级)', max_length=80),
        ),
        migrations.AddField(
            model_name='p_message',
            name='m_c_id',
            field=models.CharField(default='', help_text='关联的子类别', max_length=200),
        ),
        migrations.AddField(
            model_name='p_message',
            name='m_f_id',
            field=models.CharField(default='', help_text='关联的大类别', max_length=200),
        ),
        migrations.AlterField(
            model_name='p_message',
            name='m_address_belong',
            field=models.CharField(default='', help_text='所属地区代码（地区）', max_length=80),
        ),
    ]
