# Generated by Django 2.2.6 on 2019-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191014_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_menber_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='关联用户', max_length=30)),
                ('photo', models.CharField(help_text='营业许可证或者组织证明材料', max_length=40)),
                ('person', models.CharField(help_text='法人', max_length=20)),
                ('person_card', models.CharField(help_text='法人身份证号码', max_length=30)),
                ('person_phone', models.CharField(help_text='法人手机', max_length=20)),
                ('person_compony', models.CharField(help_text='公司/组织名称', max_length=20)),
                ('address_province', models.IntegerField(default=0, help_text='所属地区代码(省级)')),
                ('address_city', models.IntegerField(default=0, help_text='所属地区代码(市级)')),
                ('address_belong', models.IntegerField(default=0, help_text='所属地区代码（地区）')),
                ('address_detail', models.CharField(default='', help_text='详细地址', max_length=200)),
                ('contact_person', models.CharField(default='', help_text='联系人', max_length=200)),
                ('contact_phone', models.CharField(default='', help_text='联系人手机号码', max_length=200)),
                ('contact_tel', models.CharField(default='', help_text='联系人固定号码', max_length=200)),
                ('contact_email', models.CharField(default='', help_text='联系人邮箱', max_length=200)),
                ('contact_qq', models.CharField(default='', help_text='联系人QQ', max_length=200)),
            ],
        ),
    ]
