# Generated by Django 2.2.6 on 2019-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_p_menber_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_menber_auth',
            name='contact_des',
            field=models.CharField(default='', help_text='公司简介', max_length=600),
        ),
    ]
