# Generated by Django 2.2.6 on 2019-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191010_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_message_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(help_text='关联信息ID', max_length=30)),
                ('username', models.CharField(help_text='关联用户', max_length=30)),
                ('company_name', models.CharField(default='', help_text='公司名称', max_length=80)),
                ('address_province', models.CharField(default='', help_text='所属地区代码(省级)', max_length=80)),
                ('address_city', models.CharField(default='', help_text='所属地区代码(市级)', max_length=80)),
                ('address_belong', models.CharField(default='', help_text='所属地区代码（地区）', max_length=80)),
                ('address_detail', models.CharField(default='', help_text='详细地址', max_length=200)),
                ('contact_person', models.CharField(default='', help_text='联系人', max_length=200)),
                ('contact_phone', models.CharField(default='', help_text='联系人手机号码', max_length=200)),
                ('contact_tel', models.CharField(default='', help_text='联系人固定号码', max_length=200)),
                ('contact_email', models.CharField(default='', help_text='联系人邮箱', max_length=200)),
                ('contact_qq', models.CharField(default='', help_text='联系人QQ', max_length=200)),
            ],
        ),
    ]
