# Generated by Django 2.2.6 on 2019-10-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_p_menber_auth_contact_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_menber_auth',
            old_name='contact_des',
            new_name='company_des',
        ),
    ]
