# Generated by Django 2.2.6 on 2019-10-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_p_message_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_message',
            name='type',
            field=models.CharField(default=1, help_text='1：供应 2：需求', max_length=30),
        ),
    ]
