# Generated by Django 2.2.6 on 2019-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191015_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_menber_auth',
            name='auth',
            field=models.IntegerField(default=0, help_text='认证情况 1：通过 2：不通过 0：待审核'),
        ),
    ]
