# Generated by Django 2.2.6 on 2019-10-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191012_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_message_contact',
            name='auth',
        ),
        migrations.AddField(
            model_name='p_message',
            name='auth',
            field=models.IntegerField(default=1, help_text='封禁 1：正常 2：封禁'),
        ),
    ]
