# Generated by Django 2.2.6 on 2019-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191016_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_message',
            name='num',
            field=models.IntegerField(default=1, help_text='浏览人数'),
        ),
    ]
