# Generated by Django 2.2.6 on 2019-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191012_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_menber',
            name='auth',
            field=models.IntegerField(default=1, help_text='封禁 1：正常 2：封禁'),
        ),
    ]
