# Generated by Django 2.2.6 on 2019-10-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_p_message_m_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_message',
            name='m_ip',
            field=models.TextField(default='[]', help_text='ip记录'),
        ),
    ]
