# Generated by Django 2.2.6 on 2019-10-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_p_menber_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_menber',
            name='address_belong',
            field=models.IntegerField(default='', help_text='所属地区代码（地区）'),
        ),
        migrations.AlterField(
            model_name='p_menber',
            name='address_city',
            field=models.IntegerField(default='', help_text='所属地区代码(市级)'),
        ),
        migrations.AlterField(
            model_name='p_menber',
            name='address_province',
            field=models.IntegerField(default='', help_text='所属地区代码(省级)'),
        ),
        migrations.AlterField(
            model_name='p_message',
            name='m_address_belong',
            field=models.IntegerField(default='', help_text='所属地区代码（地区）'),
        ),
        migrations.AlterField(
            model_name='p_message',
            name='m_address_city',
            field=models.IntegerField(default='', help_text='所属地区代码(市级)'),
        ),
        migrations.AlterField(
            model_name='p_message',
            name='m_address_province',
            field=models.IntegerField(default='', help_text='所属地区代码(省级)'),
        ),
        migrations.AlterField(
            model_name='p_message_contact',
            name='address_belong',
            field=models.IntegerField(default='', help_text='所属地区代码（地区）'),
        ),
        migrations.AlterField(
            model_name='p_message_contact',
            name='address_city',
            field=models.IntegerField(default='', help_text='所属地区代码(市级)'),
        ),
        migrations.AlterField(
            model_name='p_message_contact',
            name='address_province',
            field=models.IntegerField(default='', help_text='所属地区代码(省级)'),
        ),
    ]
