# Generated by Django 2.2.3 on 2019-10-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191016_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_menber',
            name='file_limit',
            field=models.IntegerField(default=0, help_text='当天上传的次数'),
        ),
        migrations.AddField(
            model_name='p_menber',
            name='msg_limit',
            field=models.IntegerField(default=0, help_text='当天发表的文章次数'),
        ),
    ]
