# Generated by Django 2.2.3 on 2019-10-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_p_menber_limit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_menber',
            name='limit_time',
            field=models.CharField(default='1571453334.0664003', help_text='记录时间', max_length=30),
        ),
    ]
